import { Type } from 'class-transformer';
import {
  ArrayMinSize,
  IsArray,
  IsNotEmpty,
  IsUUID,
  ValidateNested,
} from 'class-validator';
import { CreateOrderItemDTO } from './create-order-item.dto.js';

export class CreateOrderDTO {
  // generated by the POS; resending the same id returns the same order
  @IsNotEmpty()
  @IsUUID()
  client_order_id: string;

  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => CreateOrderItemDTO)
  items: CreateOrderItemDTO[];
}
